//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 07:27:41 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mobilis.inf.tu-dresden.de/XMLEmulationScript", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tudresden.inf.rn.mobilis.gwtemulationserver.server.script;
