//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 03:47:13 PM MEZ 
//


package de.tudresden.inf.rn.mobilis.gwtemulationserver.server.script;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for setupCommandType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="setupCommandType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mobilis.inf.tu-dresden.de/XMLEmulationScript}atomicCommandType">
 *       &lt;choice>
 *         &lt;element name="instanceVarDeclaration" type="{http://mobilis.inf.tu-dresden.de/XMLEmulationScript}instanceType"/>
 *         &lt;sequence>
 *           &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element ref="{http://mobilis.inf.tu-dresden.de/XMLEmulationScript}setupMethods"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "setupCommandType", propOrder = {
    "instanceVarDeclaration",
    "instance",
    "setupMethods"
})
public class SetupCommandType
    extends AtomicCommandType
{

    protected InstanceType instanceVarDeclaration;
    protected String instance;
    @XmlElementRef(name = "setupMethods", namespace = "http://mobilis.inf.tu-dresden.de/XMLEmulationScript", type = JAXBElement.class)
    protected JAXBElement<? extends SetupMethodsType> setupMethods;

    /**
     * Gets the value of the instanceVarDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceType }
     *     
     */
    public InstanceType getInstanceVarDeclaration() {
        return instanceVarDeclaration;
    }

    /**
     * Sets the value of the instanceVarDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceType }
     *     
     */
    public void setInstanceVarDeclaration(InstanceType value) {
        this.instanceVarDeclaration = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstance(String value) {
        this.instance = value;
    }

    /**
     * Gets the value of the setupMethods property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SetupMethodsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StopType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StartType }{@code >}
     *     
     */
    public JAXBElement<? extends SetupMethodsType> getSetupMethods() {
        return setupMethods;
    }

    /**
     * Sets the value of the setupMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SetupMethodsType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StopType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StartType }{@code >}
     *     
     */
    public void setSetupMethods(JAXBElement<? extends SetupMethodsType> value) {
        this.setupMethods = ((JAXBElement<? extends SetupMethodsType> ) value);
    }

}
